name: Deploy to server

on: push

jobs:
  firts_job:
    runs-on: ubuntu-Latest
    
    steps:
        - name: Working dir
          id: step_1
          run: echo "mi_variable=Hola mundo" >> $GITHUB_OUTPUT
        
        - name: Obtener mensaje
          run: echo "${{ steps.step_1.outputs.mi_variable }}"

  second_job:
    needs: firts_job
    runs-on: ubuntu-Latest

    steps:
      - name: Hola Mundo segundo
        run: echo "Hola Mundo ${{ github.ref }}"
