name: Deploy to server

on: push

jobs:
    firts_job:
        runs-on: ubuntu-Latest

        steps:
            - name: Hola
              run: echo "Hola Mundo"

    second_job:
        if: ${{ github.ref == 'refs/heads/master' }}
        needs: firts_job
        runs-on: ubuntu-Latest

        steps:
            - name: Hola Mundo segundo
              run: echo "Hola Mundo ${{ github.ref }}"